spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/recruitosphere_auth
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update    
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka      
